### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by Linjiehua** [Thinklab-SJTU/CSL_RetinaNet_Tensorflow#1]
您好，我在训练DOTA数据集的时候发现训练了几步以后就显示显存不够。我的电脑配置和您一样有4个2080ti。我不知道问题出在了哪里，想问下您训练的时候有什么技巧吗？我只取了数据集的1/30数据进行训练，因为全部数据训练的话刚开始就报显存不够的错误了

**Comment by yangxue0827** [comment]
res50我只需要7g左右的显存

**Comment by Linjiehua** [comment]
> res50我只需要7g左右的显存

我也是用的res50，您公开的代码中cfg文件的设置我只改了路径其他的都没做修改，然后一跑训练的话就显存就占到了将近11个g了，网络训练前还有 Allocator (GPU_3_bfc) ran out of memory trying to allocate 3.38GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.的警告，但是能开始训练。不过训练几步后就显存不够了

**Comment by RyanChanli** [comment]
我训练成功了，并没有存在out of memory 的问题

**Comment by Linjiehua** [comment]
> res50我只需要7g左右的显存

我改了numpy版本后，就没有出现out of memory这个错误了

**Comment by zsh1234567** [comment]
我用的6g显存，可以正常训练，就是训练结果有点问题。某些类别结果很好，某些类别的结果就很差
This is your result for task 1:
    mAP: 0.445227836098522
    ap of each class: plane:0.8338949492486691, baseball-diamond:0.32588114881085917, bridge:0.3171791150838174, ground-track-field:0.10829184719849032, small-vehicle:0.6795921899841374, large-vehicle:0.36332757018307055, ship:0.6458500584807668, tennis-court:0.8993450906560664, basketball-court:0.522243024695198, storage-tank:0.7058845542011566, soccer-ball-field:0.04287843961877023, roundabout:0.5171141487190205, harbor:0.2772222770400146, swimming-pool:0.42310337234618534, helicopter:0.016609755211607548
