### ISSUE TITLE
评估性能时耗时很长

### ISSUE THREAD

**Issue by markAKB** [Thinklab-SJTU/CSL_RetinaNet_Tensorflow#10]
感谢您优秀的工作！我在训练结束后，进行模型的性能评估时，耗费的时间很长（大于1天），请问有什么debug的思路吗？
另外，test_dota.py文件中没有计算map的代码，是需要自行添加吗？
![图片](https://user-images.githubusercontent.com/31383717/97515979-21251300-19cd-11eb-9c82-2ff3a4a8a32f.png)

**Comment by yangxue0827** [comment]
测试命令是什么

**Comment by markAKB** [comment]
你好：
&nbsp;&nbsp;&nbsp;&nbsp; 谢谢你的回复！

&nbsp;&nbsp;&nbsp;&nbsp; 测试命令采用的是：
&nbsp;&nbsp;&nbsp;&nbsp; python test_dota.py --test_dir='/home/test/CSL_RetinaNet_Tensorflow-master/data/io/DOTA/DOTA1.0/test/images' --gpus=3,4,5,7
进度条中的图片数量约7k张，测试完成需要1-2天。



&nbsp; 祝工作顺利，身体健康！



张亚伟

西安交通大学






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Thinklab-SJTU/CSL_RetinaNet_Tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月29日(星期四) 下午3:43
收件人:&nbsp;"Thinklab-SJTU/CSL_RetinaNet_Tensorflow"<CSL_RetinaNet_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"2832454488"<2832454488@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Thinklab-SJTU/CSL_RetinaNet_Tensorflow] 评估性能时耗时很长 (#10)





 
测试命令是什么

**Comment by yangxue0827** [comment]
这个脚本是滑窗测大图的，也就是测试图片不需要自己提前裁剪好。你的测试集明显是裁剪好的小图，建议看一下测试脚本的逻辑。

**Comment by markAKB** [comment]
你好：


&nbsp; 谢谢回复！
&nbsp; 明白了!我没认真读代码，抱歉抱歉！


&nbsp; 祝工作顺利，身体健康！



张亚伟

西安交通大学






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Thinklab-SJTU/CSL_RetinaNet_Tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 上午10:24
收件人:&nbsp;"Thinklab-SJTU/CSL_RetinaNet_Tensorflow"<CSL_RetinaNet_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"2832454488"<2832454488@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Thinklab-SJTU/CSL_RetinaNet_Tensorflow] 评估性能时耗时很长 (#10)





 
这个脚本是滑窗测大图的，也就是测试图片不需要自己提前裁剪好。你的测试集明显是裁剪好的小图，建议看一下测试脚本的逻辑。

**Comment by markAKB** [comment]
那么如何计算模型在dota数据上的map呢？

**Comment by yangxue0827** [comment]
你用的DOTA测试集的话，把我测试脚本生成的结果文件提交到官网评测系统。如果用的验证集，官网也提供了评测脚本。

**Comment by markAKB** [comment]
非常感谢！
