### ISSUE TITLE
预测时多个框重叠的问题

### ISSUE THREAD

**Issue by YYL9404** [Thinklab-SJTU/CSL_RetinaNet_Tensorflow#4]
![issue](https://user-images.githubusercontent.com/37946359/94219961-914a0000-ff1a-11ea-9388-318af9a7ffd7.png)
用自己的数据训练和检测的时候发现有多个框重叠的问题

**Comment by yangxue0827** [comment]
你用的哪个测试脚本？

**Comment by YYL9404** [comment]
> 你用的哪个测试脚本？

@yangxue0827 因为测试图片较大需要裁切所以用的test_dota.py

**Comment by yangxue0827** [comment]
NMS阈值调小呢

**Comment by YYL9404** [comment]
> NMS阈值调小呢

@yangxue0827  解决了！确实是阈值调高了

**Comment by liwenjielongren** [comment]
您好，请问您的阈值设为多少，我这里也是重叠，改小还是有。

**Comment by liwenjielongren** [comment]
![image](https://user-images.githubusercontent.com/52265815/95673000-8e683400-0bd7-11eb-9068-d1b64a765f9f.png)

**Comment by yangxue0827** [comment]
不同类之间不做nms，你需要的是调置信度阈值，不是nms阈值。

**Comment by yangxue0827** [comment]
不同类之间不做nms，你需要的是调置信度阈值，不是nms阈值。

**Comment by liwenjielongren** [comment]
好的，谢谢
