### ISSUE TITLE
tf version of py_func

### ISSUE THREAD

**Issue by liujianisme** [Thinklab-SJTU/CSL_RetinaNet_Tensorflow#7]
Hi, thanks for your excellent work. i'm rencently converting this work into TensorRT deployment, but i found out that TensorRT does not support tf.py_func. Any advice about how to address this problem? Or  is it possible to rewrite these functions in tensorflow?

**Comment by yangxue0827** [comment]
Override relevant functions with TF, such as generation of anchor, etc
