### ISSUE TITLE
How can I train my datasets in coco format?

### ISSUE THREAD

**Issue by maxuetao** [Thinklab-SJTU/CSL_RetinaNet_Tensorflow#8]
Thanks for you work! I noticed that i can choose coco dataset in ./lib/config/cfgs.py. How can I start training my own dataset？I didn't find the file to convert the coco dataset to tfrecord.

**Comment by yangxue0827** [comment]
CSL is a rotation detector, the default training dataset is DOTA. CSL is not suitable for COCO training, because objects in coco have no obvious orientation information.
